public class testException2 {
    
    public static void exsception01(){
       //  try {
            Integer a = 100/0;
    //    } catch (MathException e) {
    //        System.debug(e.getTypeName() + ' was thrown in testException2! ' + e.getMessage());
    //    }
    }
    
}